version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./:/app

networks:
  default:
    external: true
    name: digitalmenu_network
